version: '3.3' 

volumes: 
  postgres_data: 
  static_value: 
  media_value: 

services: 
  db: 
    image: postgres:12.4 
    container_name: postgresql 
    volumes: 
      - postgres_data:/var/lib/postgresql/data/ 
    restart: always 
    env_file: 
      - ./.env 
  
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    build:
      context: ../backend/foodgram
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx: 
    image: nginx:1.19.3 
    restart: always 
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/  
      - static_value:/var/html/static 
      - media_value:/var/html/media 
    ports: 
      - 80:80
    depends_on: 
      - backend
      - frontend
      