# Generated by Django 2.2 on 2021-07-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210709_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
